### ISSUE TITLE
Mac Silicon installation issues

### ISSUE THREAD

**Issue by jomach** [dbt-labs/dbt-extractor#40]
Hi Guys, 

after upgrading rust and creating a virtual environment for dbt with python 3.8 I can install dbt-extractor using pip install . 
The problem is I get the error: 

(dbt-env) > $ /Users/jorge/.venv/dbt-env/bin/dbt --version                                                                                                                           [±main ✓]
Traceback (most recent call last):
  File "/Users/jorge/.venv/dbt-env/bin/dbt", line 5, in <module>
    from dbt.main import main
  File "/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt/main.py", line 13, in <module>
    import dbt.task.build as build_task
  File "/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt/task/build.py", line 1, in <module>
    from .run import RunTask, ModelRunner as run_model_runner
  File "/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt/task/run.py", line 8, in <module>
    from .compile import CompileRunner, CompileTask
  File "/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt/task/compile.py", line 2, in <module>
    from .runnable import GraphRunnableTask
  File "/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt/task/runnable.py", line 54, in <module>
    from dbt.parser.manifest import ManifestLoader
  File "/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt/parser/__init__.py", line 8, in <module>
    from .models import ModelParser  # noqa
  File "/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt/parser/models.py", line 11, in <module>
    from dbt_extractor import ExtractionError, py_extract_from_source  # type: ignore
  File "/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt_extractor/__init__.py", line 1, in <module>
    from .dbt_extractor import *
ImportError: dlopen(/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt_extractor/dbt_extractor.cpython-38-darwin.so, 0x0002): tried: '/Users/jorge/.venv/dbt-env/lib/python3.8/site-packages/dbt_extractor/dbt_extractor.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/dbt_extractor.cpython-38-darwin.so' (no such file), '/usr/lib/dbt_extractor.cpython-38-darwin.so' (no such file)

Any ideas ?

**Comment by jtcohen6** [comment]
@jomach We highly recommend you install dbt on M1 Macs via Homebrew + Rosetta, following the outline here: https://hackernoon.com/apple-m1-chip-how-to-install-homebrew-using-rosetta-su12331b. It's how I've been using dbt on my M1 Mac for a few months now, and it's been working without a hitch.

We use GitHub Actions to build wheels for this package on different system architectures. We aren't yet able to build wheels for Mac silicon architectures, because GHA does not yet support it as a runner: https://github.com/actions/virtual-environments/issues/2187
